### ISSUE TITLE
PWA Experience überarbeiten

### ISSUE THREAD

**Issue by georg-jung** [akademischerverein/ava#30]

**Comment by georg-jung** [comment]
![Screenshot_20220508-170507~2](https://user-images.githubusercontent.com/5229609/167302563-ef0bddae-0540-4083-bab3-be3d430e2e24.png)

**Comment by autoit4you** [comment]
Möchtest du das das nicht erscheint oder wie soll man dieses Issue verstehen?

**Comment by georg-jung** [comment]
Ich möchte, dass da kein generisches Logo und kein technischer Name steht. Fixed by 9ab8954ad1eef466668d24de691cd9dc2dea2cd9
